### ISSUE TITLE
Upgrade CI setting

### ISSUE THREAD

**Issue by peter279k** [mpscholten/typesafe-enum#1]
It seems that this CI build is under the Circle CI `1.0` build.

But it has been the `2.0` for about while.

I think it's time to upgrade Circle CI to `2.0` now and create `.cirecle` directory and add the config.yml` setting file.

@mpscholten, what do you think about this?

**Comment by mpscholten** [comment]
Agree, in case you can provide a PR, I'm happy to merge it!

**Comment by peter279k** [comment]
@mpscholten. If possible, please add `#orbtoberfest` on this issue because of the [hacktoberfest circleci](https://hacktoberfest.circleci.com) :).

**Comment by mpscholten** [comment]
Thanks for letting me know! :) Just added the labels.

**Comment by mpscholten** [comment]
Thanks again for fixing :)
