### ISSUE TITLE
Upgrading PHP version supports

### ISSUE THREAD

**Issue by peter279k** [mpscholten/typesafe-enum#3]
As title, this repository should upgrade PHP version supports.

IMHO, I think we can consider letting this repository require `php-7.1` version at least.

And also upgrading `PHPUnit` dependencies :).

@mpscholten. If possible, please add `orbtoberfest` on this issue because of the [hacktoberfest circleci](https://hacktoberfest.circleci.com) :).

**Comment by mpscholten** [comment]
Thanks, feel free to update it. Happy to merge :) 🚀

**Comment by mpscholten** [comment]
Fixed via #4
